foodapp/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eco/', include('ecomeals.urls')),
    path('budget/', include('budgetgroceries.urls')),
    path('preferences/', include('dietpreferences.urls')),
    path('mealsuggestions/', include('mealsuggestions.urls')),
    path('', include('userapp.urls')),
    path('register/', views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    path('profile', views.profile, name = 'profile'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mealsuggestions/urls.py
from django.urls import path
from . import views

app_name = 'mealsuggestions' 

urlpatterns = [
    path('', views.meal_suggestions, name='meal_suggestions'),
]

userapp/urls.py
from django.urls import path
from . import views
from .views import MealRecommendationView
from userapp.views import contact, success, planner_page, food_article

app_name = 'userapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact/', contact, name='contact'),
    path('success/', success, name='success'),
    path('meals/', views.meals, name='meals'),
    path('api/recommendations/', MealRecommendationView.as_view(), name='meal-recommendations'),
    path('planner/', planner_page, name='planner_page'),
    path('foodarticle/', food_article, name='food_article'),
]

userapp/forms.py
from django import forms
from django.core.validators import EmailValidator

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(validators=[EmailValidator()])
    message = forms.CharField(widget=forms.Textarea)
    

userapp/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from userapp.forms import ContactForm
from .forms import ContactForm
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import QuestionnaireSerializer
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'userapp/home.html', {'title': 'Welcome'})

def about(request):
    return render(request, 'userapp/about.html', {'title': 'About'})

@login_required
def meals(request):
    return render(request, 'userapp/meals.html')

def planner_page(request):
    return redirect("https://spoonacular.com/meal-planner")

def food_article(request):
    return redirect("https://spoonacular.com/articles")

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            
            EmailMessage(
                'Student Contact Submission from {}'.format(name),
                message,
                'form-response@example.com',
                ['declanchambers666@gmail.com'],
                reply_to=[email]
            ).send()
            return redirect ('userapp:success')
    else:
        form = ContactForm()        
    return render(request, 'userapp/contact.html', {'form': form})
    
def success(request):
    return render(request, 'userapp/success.html')

class MealRecommendationView(APIView):
    def post(self, request):
        serializer = QuestionnaireSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        # Extract user inputs
        preferences = serializer.validated_data.get('preferences', [])
        allergies = serializer.validated_data.get('allergies', [])
        budget = serializer.validated_data.get('budget')
        eco_friendly = serializer.validated_data.get('eco_friendly', False)
        max_calories = serializer.validated_data.get('max_calories')
        
        redirect_url = self._get_redirect_url(preferences, allergies, budget, eco_friendly, max_calories)
        return Response({'redirect_url': redirect_url})    
    
    def _get_redirect_url(self, preferences, allergies, budget, eco_friendly, max_calories):
        if eco_friendly:
            return "/eco/"
        
        if allergies:
            allergy_tags = ','.join(allergies)
            return f"/mealsuggestions/?exclude_allergens={allergy_tags}"

        if preferences:
            diet = preferences[0]
            return f"/preferences/?filter={diet}"

        if budget:
            return f"/budget/?max_price={budget}"

        diet = preferences[0] if preferences else "chicken"
        return f"/mealsuggestions/?query={diet}&cheap=true&max_calories={max_calories or 600}"
    
    
    
    

userapp/templates/userapp/about.html
{% extends "userapp/base.html" %}
{% block content %}
<div class="container mt-4">
    <h1>About the Food App</h1>

    <br>

    <p class="lead">This app helps students eat well, save money, and live sustainably.</p>

    <h3 class="mt-4">How This App Works</h3>
    <p>This smart food app allows Students to plan and enter there Featured Preferences:</p>
    <ul class="list-group mb-5">
        <li class="list-group-item">Pensonalised Meal Recommendations</li>
        <li class="list-group-item">Filtering results for things like allergies, budgets and eco-values </li> 
        <li class="list-group-item">Deal Grocery insights by Locations</li>
    </ul>

    <h3 class="mt-5">This was Built with</h3>
    <ul class="list-group mb-5">
        <li class="list-group-item">Django and Rest Framework</li>
        <li class="list-group-item">Bootstrap 5 into responsive UI</li>
        <li class="list-group-item">Spoonacular and SendGrid APIs for recipes and Nearby Stores</li>
    </ul>
</div>
{% endblock %}

userapp/templates/userapp/base.html
{% load static %}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}

<!DOCTYPE html>
<html>

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>Student IT Services - {{title}}</title>
</head>
<body>
    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'userapp:home' %}">Food IT Services</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-
                    target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- LEFT NAVBAR -->
                     <div class="navbar-nav me-auto">
                        <a class="nav-item nav-link" href="{% url 'userapp:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'userapp:about' %}">About</a>
                        <a class="nav-item nav-link" href="{% url 'userapp:contact' %}">Contact</a>

                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'userapp:meals' %}">Meals</a>
                    {% endif %}
                    
                    </div>
                    
                    <!-- RIGHT NAVBAR -->
                     <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <form method="post" id="frm_logout" action="{% url 'logout' %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-item nav-link" style="background:none; border:none;">Logout</button>
                        </form>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div class="col-md-8">
            {% block content %}{% endblock %}
        </div>
        {% if user.is_authenticated %}
        <div class="col-md-4">
            <div class="content-section">
                <h3>Student Meal Planning</h3>
                <p class='text-muted'>Quick links to key features:</p>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'mealsuggestions:meal_suggestions' %}">Meal Suggestions</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'budget_groceries' %}">Budget Groceries</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'diet_preferences' %}">Diet Preferences</a>
                    </li>
                    <li class="list-group-item list-group-item-light">
                        <a href="{% url 'eco_meals' %}">Eco Meals</a>
                    </li>
                </ul>                
            </div>
        </div>
        {% endif %}
    </div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
crossorigin="anonymous"></script>
</body>
{% block extra_scripts %}
{% endblock %}
</html>

userapp/templates/userapp/contact.html
{% extends "userapp/base.html" %}
{% block content %}
    <form action="/contact/" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <input type="submit" value="Submit">
        </form> 
{% endblock %}

userapp/templates/userapp/foodarticle.html
{% extends "userapp/base.html" %}
{% block content %}
<h2> Please search these Food Articles Today</h2>
<iframe src="https://spoonacular.com/articles" width="100%" height="600px"></iframe>
{% endblock %}

userapp/templates/userapp/home.html
{% extends "userapp/base.html" %}

{% block content %}

    <h1>Welcome to Declan's Smart Food App</h1>

    <br>

    <p2>This app helps students to find cheap and affordalble meals using:</p>

    <h2 class="mt-3">Features</h2>
    <ul class="list-group mb-5">
        <li class="list-group-item">Tasty Meal suggestions tailored to you</li>
        <li class="list-group-item">Locations near you for Budget Groceries</li>        
        <li class="list-group-item">Eco-Friendly meal choses</li>
        <li class="list-group-item">Diet Preferences and Filtering Allergies</li>
    </ul>

    <h3 class="mb-4">Benefits for Students</h3>

    <div class="row text-center">
        <div class="col-md-4 mb-4">
            <a href="{% url 'userapp:planner_page' %}" class="btn btn-outline-primary btn-block">
                <h5 class="mb-3"> This is your Weekly Planner </h5>
                <p class="mb-3"> Here is your Weekly Planner - To help Plan your Meals in Time and Budget </p>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="{% url 'userapp:food_article' %}" class="btn btn-outline-primary btn-block">
                <h5 class="mb-3"> Check the Latest Articles Today </h5>
                <p class="mb-3">  Here is your Wide range of Food Articles for you today! </p>
            </a>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md 6">
            <h3>Top Meals Today!</h3>
            <div class="card" style="width: 100%;">
                <img src="https://spoonacular.com/recipeImages/716426-312x231.jpg" class="card-img-top" alt="Top Meal">
                <div class="card-body">
                    <h5 class="card-title">Simple Grilled Chicken Bowl</h5>                    
                    <p class="card-text">A healthy, protein that is easy-to-cook protein meal.</p>
                    <a href="https://spoonacular.com/recipes/simple-grilled-chicken-bowl-716426" 
                    target="_blank" class="btn btn-primary">View the Recipe</a>
                </div>
            </div>
        </div>
    </div>

    <h3 class="mt-4">Top Weekly Picks</h3>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-3">
                <img src="https://spoonacular.com/recipeImages/652417-312x231.jpg" class="card-img-top" alt="One-Pot Spaghetti">
                <div class="card-body">
                    <h5 class="card-title">Easy One-Pot Spaghetti</h5>
                    <p class="card-text">One-pot dish with rich tomato flavor. This is perfect for busy students!</p>
                    <a href="https://spoonacular.com/recipes/easy-one-pot-spaghetti-652417" 
                    target="_blank" class="btn btn-success">See recipe</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card mb-3">
                <img src="https://spoonacular.com/recipeImages/716429-312x231.jpg" class="card-img-top" alt="Pesto Pasta">
                <div class="card-body">
                    <h5 class="card-title">Creamy Pesto Pasta</h5>
                    <p class="card-text">Affordable, Creamy and easy to make Meal.</p>
                    <a href="https://spoonacular.com/recipes/pasta-with-garlic-scapes-pesto-716429" 
                    target="_blank" class="btn btn-success">See Recipe</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card mb-3">
                <img src="https://spoonacular.com/recipeImages/658509-312x231.jpg" class="card-img-top" alt="Veggie Stir Fry">
                <div class="card-body">
                    <h5 class="card-title">Veggie Stir-Fry Bowl</h5>
                    <p class="card-text"> Nutritious Sustainable Meal with Veggie-packed stir Fry</p>
                    <a href="https://spoonacular.com/recipes/spring-veggie-stir-fry-bowl-658509" 
                    target="_blank" class="btn btn-success">See Recipe</a>
            </div>
        </div>

{% endblock %}

userapp/templates/userapp/meals.html
{% extends "userapp/base.html" %}
{% block content %}

<h1>Smart Meal Questionnaire</h1>
<p>Answer a few questions and we’ll suggest the best meals or pages.</p>

  {% csrf_token %}
<form id="questionnaire-form" class="container mt-4">
  <div class="row mb-3">
    <div class="col-md-5">   
      <h3>Dietary Preferences</h3>
      <select name="preferences" multiple class="form-control">
        <option value="vegan">Vegan</option>
        <option value="vegetarian">Vegetarian</option>
        <option value="keto">Keto</option>
        <option value="gluten_free">Gluten-Free</option>
      </select>
    </div>

    <div class="col-md-5">     
      <h3>Allergies</h3>
      <select name="allergies" multiple class="form-control" id="allergies">
        <option value="nuts">Nuts</option>
        <option value="dairy">Dairy</option>
        <option value="seafood">Seafood</option>
      </select>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-5">
      <h3>Budget</h3>
      <input type="number" name="budget" placeholder="Max Budget" class="form-control">
    </div>

    <div class="row-mb-3">
      <h3>Eco-Friendly</h3>
      <div class="form-check">
        <input type="checkbox" name="eco_friendly" class="form-check-input" id="ecoCheck"> 
        <label class="form-check-label" for="ecoCheck"> Prefer eco-friendly meals</label>

  <br><br>
  <button type="submit" class="btn btn-primary">Get Recommendations</button>
</form>

<script>
  document.getElementById('questionnaire-form').addEventListener('submit', async (e) => {
    e.preventDefault();

    const formData = new FormData(e.target);
    const data = Object.fromEntries(formData.entries());

    data.preferences = formData.getAll('preferences');
    data.allergies = formData.getAll('allergies');
    data.eco_friendly = formData.has('eco_friendly');

    const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    const response = await fetch('/api/recommendations/', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrfToken
      },
      body: JSON.stringify(data)
    });

    const result = await response.json();
    if (result.redirect_url) {
      window.location.href = result.redirect_url;
    }
  });
</script>

{% endblock %}

userapp/templates/userapp/planner.html
{% extends "userapp/base.html" %}
{% block content %}
<h2> This is your Weekly Planner</h2>
<iframe src="https://spoonacular.com/meal-planner" width="100%" height="500px"></iframe>
{% endblock %}

userapp/templates/userapp/success.html
{% extends "userapp/base.html" %}

{% block content %}
<div class="success-message">
    <h1>Successful!</h1>

    <p>Your message was completed successfully.</p>
    <br>
    <a href="{% url 'userapp:home' %}">← Return to Home</a>
</div>


<style>
    .success-message {
        text-align: center;
        padding: 20px;
        border: 2px solid #4caf50;
        border-radius: 5px;
        background-color: #dff0d8;
        color: #3c763d;
        }
</style>

{% endblock %}